### PR TITLE
Management View

### PR DESCRIPTION
**Pull request by shuhaowu**
I'm in the process of migrating towards using `$http` as oppose to `jQuery.ajax`.

Same thing for `$q` vs `jQuery.Defered`, but there is no instance of that here.

The management view consists of just a view to add and delete members. This should be fine for now. 

Addresses #21

### CODE REVIEW

**Comment by travellingprog** [comment]
II'll take a look at this tomorrow evening

**Comment by travellingprog** [comment]
Are `prompt("Enter an email address:")` and `confirm("Are you sure you want to delete this user?")` supposed to do something? Because in what I'm looking at, those two functions don't seem to be defined. Your code seems fine, but I can't do a real-use test.

**Comment by shuhaowu** [comment]
These are built in functions provided by the DOM. Try it!

Shuhao

**Comment by travellingprog** [comment]
you're right, I can use them from Console. Weird, nothing was happening this morning when I clicked on the first Add button. I'll try it again later.

**Comment by travellingprog** [comment]
Yeah, so I dunno what was going on this morning, but it's working fine now and I didn't change anything... strange

:+1:

**Comment by shuhaowu** [comment]
Thanks for the review!

**Pull request merged**
